# GoReleaser configuration for apt-exporter
version: 2
project_name: apt-exporter

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/apt-exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

# Snapshot configuration
snapshot:
  name_template: "{{ incpatch .Version }}-next"

archives:
  -
    # Use the default format (tar.gz for linux/macos, zip for windows)
    files:
      - LICENSE
      - README.md
      - config.yml

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: ncecere
    name: apt-exporter
  prerelease: auto
  draft: false
  name_template: "Release {{.Version}}"
